[package]
name = "keru_subsecond"
version = "0.1.0"
edition = "2024"

[dependencies]
keru = { path = "../.." }
winit = { version = "0.30.5", features = ["rwh_05"] }
wgpu = { version = "27", default-features = true }
dioxus-devtools = { version = "0.7.3", features = ["serve"] }
